project_name: kubepug
release:
  github:
    owner: rikatz
    name: kubepug

builds:
  - id: kubepug
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - arm64
    - arm
    - s390x
    - ppc64le
    goarm:
      - 7
    ignore:
    - goos: windows
      goarch: arm64
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: s390x
    - goos: windows
      goarch: ppc64le
    flags:
    - -trimpath
    ldflags:
    - "{{ .Env.LDFLAGS }}"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOPROXY=https://proxy.golang.org
    main: .
    binary: output/kubepug

archives:
  - id: kubepug
    builds:
    - kubepug
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
    - goos: windows
      format: zip
