defaultBaseImage: cgr.dev/chainguard/static:latest

builds:
  - id: kubepug
    dir: .
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags
      - "{{ .Env.GIT_HASH }}"
      - -tags
      - "{{ .Env.GIT_VERSION }}"
    ldflags:
      - -extldflags "-static"
      - "{{ .Env.LDFLAGS }}"
