name: ci
on:
  pull_request:
    branches:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # v3
      with:
        go-version: 1.18
        check-latest: true
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3

    - name: Add GOPATH/bin to PATH
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: go mod download

    - name: Ensure go.mod is already tidied
      run: go mod tidy && git diff --no-patch --exit-code

    - name: Run Unit Tests
      run: make test

    - name: Verify building
      run: make build

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757 # v3
      with:
        install-only: true

    - name: Verify goreleaser
      run: make snapshot
