name: ci
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: "1.20"
          check-latest: true

      - name: Add GOPATH/bin to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          go mod download
          sudo apt-get install -y lcov

      - name: Ensure go.mod is already tidied
        run: go mod tidy && git diff --no-patch --exit-code

      - name: Run Unit Tests
        run: make test
      
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@c680c0f7c7442485f1749eb2a13e54a686e76eb5 # v1.0.9
        with:
          version: v1.0.5

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@73c068acfc6a265af813132fbca7ef8738a1f52f # v3.1.8
        with:
          coverage-files: coverage.lcov
          artifact-name: code-coverage-report
          update-comment: true

      - name: Verify building
        run: make build

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@336e29918d653399e599bfca99fadc1d7ffbc9f7 # v4.3.0
        with:
          install-only: true

      - name: Verify goreleaser
        run: make snapshot

      - run: ./dist/kubepug_linux_amd64_v1/kubepug version
