name: ci
on:
  pull_request:
    branches:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v3
      with:
        go-version: 1.18
        check-latest: true
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3

    - name: Add GOPATH/bin to PATH
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: go mod download

    - name: Ensure go.mod is already tidied
      run: go mod tidy && git diff --no-patch --exit-code

    - name: Run Unit Tests
      run: make test

    - name: Verify building
      run: make build

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@68acf3b1adf004ac9c2f0a4259e85c5f66e99bef # v3
      with:
        install-only: true

    - name: Verify goreleaser
      run: make snapshot
