name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3

      - uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # v3
        with:
          go-version: 1.18
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376 # v3
        with:
          version: v1.46.2
